spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    alicloud:
      access-key: LTAI4FzhuX1rFQt2yWDmgwsn
      secret-key: z3ZFoNHoCaG1V1qmQ32Dm4OTLNP5fA
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: wts-gulimall
      sms:
        host: https://fsmsn.market.alicloudapi.com
        path: /fsms132
        skin: 1
        sign: 1
        appcode: 51d31e027fbf47a2b15a569cf88ddbb4
  application:
    name: gulimall-thrid-party
server:
  port: 30000
